services:
  srt-to-audio-elevenlabs-api:
    image: xuongkienphung/srt-to-audio-elevenlabs-api:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
      - ./db.json:/app/db.json
    environment:
      - PYTHONUNBUFFERED=1
