name: srt-audio-env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pydub
  - pip:
      - pysrt
      - fastapi
      - python-dotenv
      - elevenlabs
      - scalar-fastapi
      - python-multipart
      - uvicorn
